name: Build and Deploy to Sandbox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Stamp artifact file name with commit hash
      run: |
        set -euo pipefail
        artifact=$(ls target/*.jar | head -n1)
        commitHash=${GITHUB_SHA::7}
        newArtifact="${artifact%.jar}-$commitHash.jar"
        mv "$artifact" "$newArtifact"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - uses: actions/download-artifact@v4
      with:
        name: artifacts
        path: .
    - name: Deploy to Sandbox
      env:
        USERNAME: ${{ secrets.anypoint_platform_username }}
        PASSWORD: ${{ secrets.anypoint_platform_password }}
        CONNECTED_CLIENT_ID: ${{ secrets.connected_client_id }}
        CONNECTED_CLIENT_SECRET: ${{ secrets.connected_client_secret }}
        ENVIRONMENT: ${{ secrets.anypoint_environment }}
        APP_NAME: ${{ secrets.APP_NAME }}
      run: |
        set -euo pipefail
        artifactName=$(ls *.jar | head -n1)
        mvn clean deploy -DmuleDeploy \
          -Dmule.artifact="$artifactName" \
          -Danypoint.username="$USERNAME" \
          -Danypoint.password="$PASSWORD" \
          -Dap.conn.app.client.id="$CONNECTED_CLIENT_ID" \
          -Dap.conn.app.client.secret="$CONNECTED_CLIENT_SECRET" \
          -Dapp.name="$APP_NAME" \
          -Dapp.env="$ENVIRONMENT"